/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module vg (
  input clock50MHz_i,
  input resetn_i,
  input p1_select_i,
  input p1_start_i,
  input p1_up_i,
  input p1_down_i,
  input p1_left_i,
  input p1_right_i,
  input p1_button1_i,
  input p1_button2_i,
  input p1_button6_i,
  input p1_button3_i,
  input p1_button4_i,
  input p1_button5_i,
  input p2_select_i,
  input p2_start_i,
  input p2_up_i,
  input p2_down_i,
  input p2_left_i,
  input p2_right_i,
  input p2_button1_i,
  input p2_button2_i,
  input p2_button6_i,
  input p2_button3_i,
  input p2_button4_i,
  input p2_button5_i,
  input [15:0] switch_i,
  input [31:0] wb_data_i,
  input wb_ack_i,
  input dmi_req_valid_i,
  input [6:0] dmi_req_address_i,
  input [31:0] dmi_req_data_i,
  input [1:0] dmi_req_op_i,
  input dmi_rsp_ready_i,
  output [7:0] v_r_o,
  output [7:0] v_g_o,
  output [7:0] v_b_o,
  output v_vs_o,
  output v_hs_o,
  output v_clk_o,
  output [11:0] v_x_o,
  output [11:0] v_y_o,
  output v_de_o,
  output [15:0] a_left_o,
  output [15:0] a_right_o,
  output a_clk_o,
  output [15:0] led_o,
  output [63:0] seg_o,
  output [31:0] wb_adr_o,
  output [31:0] wb_dat_o,
  output wb_we_o,
  output [3:0] wb_sel_o,
  output wb_stb_o,
  output wb_cyc_o,
  output dmi_req_ready_o,
  output dmi_rsp_valid_o,
  output [31:0] dmi_rsp_data_o,
  output [1:0] dmi_rsp_op_o
);
  assign v_r_o = 8'b0;
  assign v_vs_o = 1'b0;
  assign v_x_o = 12'b0;
  assign a_left_o = 16'b0;
  assign seg_o = 64'b0;
  assign wb_adr_o = 32'b0;
  assign wb_sel_o = 4'b0;
  assign dmi_rsp_op_o = 2'b0;
endmodule
